<?php
/*
 * Implementation of hook_form_views_exposed_form_alter
 */
function drupalse_custom_form_views_exposed_form_alter(&$form, $form_state) {

   switch ($form['#id']){
   case 'views-exposed-form-showcase-page-1':
     $form['national']['#options']['0'] = t('Foreign or international website');
     $form['national']['#options']['1'] = t('Swedish website');
   break;
   }
}

/*
* Implementation of a Drupal action.
* Disable comments for a node.*
*/
function action_node_disable_comments($op, $edit = array(), &$node) {
  switch($op) {
    case 'metadata':
      return array(
        'description' => t('Disable comments for node'),
        'type' => t('Node'),
        'batchable' => true,
        'configurable' => false,
      );

    case 'do':
      $node->comment = '0';
      if (!$edit['defer']) {
        node_save($node);
      }
      watchdog('action', t('Disabed comments on node id %id', array('%id' => intval($node->nid))));
      break;

    // process the HTML form to store configuration
    case 'submit':
      return '';
  }
}
