<?php
// $Id$
// Copyright (c) 2010 KontextWork GbR
// Author: Eugen Mayer

/**
 * Implementation of hook_imagecache_default_presets().
 */
function wysiwyg_imageupload_browser_imagecache_default_presets() {
  $presets = array();
  $presets['wysiwyg_imageupload_browser_preview'] = array(
    'presetname' => 'wysiwyg_imageupload_browser_preview',
    'actions' => array(
      0 => array(
      'weight' => '0',
      'module' => 'imagecache',
      'action' => 'imagecache_scale',
      'data' => array(
        'width' => '120',
        'height' => '120',
        'upscale' => 1,
      ),
      ),
    )
  );
  return $presets;
}

/**
 * Implementation of hook_menu().
 */
function wysiwyg_imageupload_browser_menu() {
  $items = array();
  $items['ajax/wysiwyg_imageupload_browser/%'] = array(
    'page callback' => 'wysiwyg_imageupload_browser_browser',
    'page arguments' => array(2),
    'access callback' => 'user_access',
    'access arguments' => array('use wysiwyg image upload'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_form_alter().
 */
function wysiwyg_imageupload_browser_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'wysiwyg_imageupload_upload_form' ||  $form_id == 'wysiwyg_imageupload_edit_form') {
    $tabs = array();
    $tabs[] = '<a href="#">' . t('New Image') . '</a>';
    $tabs[] = l(t('Browser'), 'ajax/wysiwyg_imageupload_browser/' . $form["#parameters"][2], array('title' => t('Choose a new image out of all your already uploaded ones')));
    $form['browse'] = array(
      '#value' => _wysiwyg_imageupload_browser_tabs($tabs, 0),
      '#weight' => 0,
      '#prefix' => '<div id="wysiwyg_imagepload_tabnav" class="clearfix">',
      '#suffix' => '</div>',
    );
  }
}

/**
 * Generate the Browser
 */
function wysiwyg_imageupload_browser_browser($form_id) {
  global $user, $base_url;
  jquery_ui_dialog_child_js();
  module_invoke('admin_menu', 'suppress');

  // Adding tabs.
  $tabs = array();
  $parent_build_id = arg(2);
  $tabs[] = l(t('New Image'), 'wysiwyg_imageupload/upload/' . $parent_build_id, array('title' => t('Go back to the upload form and upload a new image')));
  $tabs[] = '<a href="#">' . t('Browser') . '</a>';
  $output .= _wysiwyg_imageupload_browser_tabs($tabs, 1);
  $output .= '<div id="wysiwyg_imageupload_browser_group" class="clearfix">';
  $output .= views_embed_view('wysiwyg_imageupload_browser', 'default', $parent_build_id);
  $output .= '</div>';

  return $output;
}

function _wysiwyg_imageupload_browser_tabs($tabs, $active) {
  $m = drupal_get_path('module', 'wysiwyg_imageupload_browser');
  drupal_add_css($m . '/wysiwyg_imageupload_browser.css');

  $output .= '<ul class="wysiwyg_imageupload_tabs clearfix">';
  foreach ($tabs as $index => $tab) {
    if ($index == $active) {
      $class = 'active';
    }
    else {
      $class = 'inactive';
    }
    $output .= '<li class="wysiwyg_imageupload_tab wysiwyg_imageupload_tab_' . $class . '">' . $tab . '</li>';
  }
  $output .= '</ul>';
  return $output;
}

/**
 * Implements hook_views_api().
 */
function wysiwyg_imageupload_browser_views_api() {
  return array(
    'api' => 2.0,
  );
}

